name: refl_maths
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - numpy
  - scipy
  - snakemake
  - pip=19.1.1
  - python=3.6.8
  - pip:
    - refnx
    - emcee
    - seaborn
